version : '3'

services:
    api:
        build: ./.docker/app/
        container_name: api
        entrypoint: dockerize -template ./.docker/httpd/apache2.conf:/etc/apache2/apache2.conf   -template ./.docker/app/db.php:/var/www/config/db.php  -wait tcp://db-api:3306 -timeout 40s ./.docker/entrypoint.sh
        environment: 
            - DB_HOST=db-api
            - DB_DATABASE=api
            - DB_USERNAME=root
            - DB_PASSWORD=root
        volumes: 
            - .:/var/www
        networks:
            - app-networks-api
        depends_on:
            - db-api
        ports:
            - "8090:80"
    db-api:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db-api
        restart: always
        tty: true
        ports: 
            - "33006:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=api
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks:
            - app-networks-api   
    adminer-api:
        image: adminer
        container_name: adminer-api
        restart: always
        ports:
            - 8008:8080 
        networks:
            - app-networks-api   
            
networks:
    app-networks-api:
        driver: bridge